---
title: "In class Exercise 6"
format:
  html:
    code-fold: true
    code-summary: "Show the code"

execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
date: "`r Sys.Date()`"
---

```{r}
pacman::p_load(sf, tmap, tidyverse, sfdep)
```

```{r}
#| code-fold: true
#| code-summary: "Show the Code"

hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

::: callout-note hello

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunanGDPPC <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)
```

```{r}
tmap_mode("plot")
tm_shape(hunanGDPPC) +
  tm_fill("GDPPC", 
          style = "quantile", 
          title = "GDP per capita") +
  tm_layout(main.title = "Distribution of GDP per capita by ...",
            main.title.size = 1.5,
            main.title.position = "center")+
  tm_borders(alpha = 0.2)+
  tm_compass(type = "8star", size = 2)+
  tm_scale_bar()+
  tm_grid(alpha = 0.2)
```

```{r}
# nb is neighbour and wt is weight
# we use st_contiguity to create a neighbour object from geometry. 
# Then we use st_weights to create a weight object from the neighbour object.
# .before = 1 will put inside from the first column 

wm_q <- hunanGDPPC %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb, 
                        style = "W"),
         .before = 1)
```

moran I

```{r}
global_moran_test(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt)
```

now, since people will question your wj we will use permutate to test the significance of the moran I

```{r}

global_moran_perm(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt,
                 nsim = 99)
```

:::callout note Te number of simulation is always equal to nsim +! this mean in nsim = 99 this mean 100 simulations will be
